# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Practice_mode_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shiftButton = QtWidgets.QPushButton(self.centralwidget)
        self.shiftButton.setGeometry(QtCore.QRect(100, 20, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shiftButton.setFont(font)
        self.shiftButton.setObjectName("shiftButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.changeButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeButton.setGeometry(QtCore.QRect(600, 30, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.changeButton.setFont(font)
        self.changeButton.setObjectName("changeButton")
        self.explain = QtWidgets.QTextEdit(self.centralwidget)
        self.explain.setGeometry(QtCore.QRect(100, 170, 600, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.explain.setFont(font)
        self.explain.setReadOnly(True)
        self.explain.setObjectName("explain")
        self.word = QtWidgets.QLabel(self.centralwidget)
        self.word.setGeometry(QtCore.QRect(200, 110, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.word.setFont(font)
        self.word.setText("")
        self.word.setAlignment(QtCore.Qt.AlignCenter)
        self.word.setObjectName("word")
        self.showButton = QtWidgets.QPushButton(self.centralwidget)
        self.showButton.setGeometry(QtCore.QRect(100, 500, 100, 30))
        self.showButton.setObjectName("showButton")
        self.coverButton = QtWidgets.QPushButton(self.centralwidget)
        self.coverButton.setGeometry(QtCore.QRect(350, 500, 100, 30))
        self.coverButton.setObjectName("coverButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(600, 500, 100, 30))
        self.nextButton.setObjectName("nextButton")
        self.count = QtWidgets.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(350, 550, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.count.setFont(font)
        self.count.setText("")
        self.count.setObjectName("count")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 45, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fromBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fromBox.setGeometry(QtCore.QRect(150, 70, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fromBox.setFont(font)
        self.fromBox.setMaximum(3000)
        self.fromBox.setObjectName("fromBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 25, 25))
        self.label_3.setObjectName("label_3")
        self.toBox = QtWidgets.QSpinBox(self.centralwidget)
        self.toBox.setGeometry(QtCore.QRect(235, 70, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toBox.setFont(font)
        self.toBox.setMaximum(3000)
        self.toBox.setObjectName("toBox")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(320, 70, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GRE_Helper"))
        self.shiftButton.setText(_translate("MainWindow", "ShiftMode"))
        self.label.setText(_translate("MainWindow", "Practice Mode"))
        self.changeButton.setText(_translate("MainWindow", "Random"))
        self.showButton.setText(_translate("MainWindow", "Show"))
        self.coverButton.setText(_translate("MainWindow", "Cover"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.label_2.setText(_translate("MainWindow", "From"))
        self.label_3.setText(_translate("MainWindow", "To"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
